version: 2

jobs:
  build:
    environment:
      - MIX_ENV: "test"
    docker:
      # Use CircleCI specific images:
      # - provide `dockerize` used command below
      # - for more information see https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/elixir:1.7.3
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_DB: eventstore_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/repo
    steps:
      - checkout
      - run: cp config/test.circle.exs config/test.exs
      - run: mix do local.hex --force, local.rebar --force
      - restore_cache: # restore saved dependency cache
          keys:
            - v1-dep-cache-{{ checksum "mix.lock" }}
            - v1-dep-cache-{{ .Branch }}
            - v1-dep-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-and-mix-cache-{{ .Branch }}
            - v1-build-and-mix-cache
      - run: mix do deps.get, compile --warnings-as-errors
      - save_cache: # save dependencies to cache
          key: v1-dep-cache-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache: # save dependencies to cache
          key: v1-dep-cache-{{ .Branch }}
          paths: "deps"
      - save_cache: # save dependencies to cache
          key: v1-dep-cache
          paths: "deps"
      - save_cache: # save build cache
          key: v1-build-and-mix-cache-{{ .Branch }}
          paths:
            - _build
            - ~/.mix
      - save_cache: # save build cache
          key: v4-build-and-mix-cache
          paths:
            - _build
            - ~/.mix
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix hex.audit
      - run: mix format --check-formatted
      - run: mix do event_store.create, event_store.init
      - run: mix test
